# Generated by Django 5.1.6 on 2025-02-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='UTC', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
